REM INSERTING into WS4TI.ALL_ESTADOS
SET DEFINE OFF;
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('RO','Rondônia');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('AC','Acre');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('AM','Amazonas');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('RR','Roraima');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('PA','Pará');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('AP','Amapá');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('TO','Tocantins');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('MA','Maranhão');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('PI','Piauí');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('CE','Ceará');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('RN','Rio Grande do Norte');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('PB','Paraíba');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('PE','Pernambuco');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('AL','Alagoas');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('SE','Sergipe');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('BA','Bahia');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('MG','Minas Gerais');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('ES','Espírito Santo');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('RJ','Rio de Janeiro');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('SP','São Paulo');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('PR','Paraná');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('SC','Santa Catarina');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('RS','Rio Grande do Sul');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('MS','Mato Grosso do Sul');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('MT','Mato Grosso');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('GO','Goiás');
Insert into WS4TI.ALL_ESTADOS (CD_UF,NM_ESTADO) values ('DF','Distrito Federal');
