REM INSERTING into WS4TI.ALL_PAIS
SET DEFINE OFF;
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AR','Argentina');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AS','Samoa Americana');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AT','Austria');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AU','Australia');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AW','Aruba');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AZ','Azerbaijão');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BA','Bosnia Herzegovinia');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BB','Barbados');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BD','Bangladesh');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BE','Bélgica');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BF','Burkina Fasso');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BG','Bulgária');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BH','Bahrain');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BI','Burundi');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BJ','Benin');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BM','Bermudas');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BN','Brunei');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BO','Bolivia');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BR','Brasil');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BS','Bahamas');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BT','Butão');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BV','Bouvet Island');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BW','Botswana');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BY','Belarus (Bielorússia)');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('BZ','Belize');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AD','Andorra');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AE','Emirados Arabes');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AF','Afeganistão');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AL','Albânia');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AM','Armenia');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AN','Hantilhas Holandesas');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('AO','Angola');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('RU','Ruanda');
Insert into WS4TI.ALL_PAIS (CD_PAIS,DS_PAIS) values ('EX','EXTERIOR');
