REM INSERTING into WS4TI.CLIENTE_MAQUINA_ARQUIVO
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_MAQUINA_ARQUIVO (ID_CLIENTE,CD_MAQUINA,ID_ARQUIVO,NOME_ARQUIVO,DESCRICAO_ARQUIVO,MIME_TYPE_ARQUIVO,CHARSET_ARQUIVO,UPDATE_DATE,CD_USUARIO) values ('1','ALIM_MP03','1','all_cidade_data.sql','teste','application/x-sql',null,to_date('20/03/18','DD/MM/RR'),'lcosta');
