REM INSERTING into WS4TI.CLIENTE_CALENDARIO
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('21/04/17','DD/MM/RR'),null,null,'Tiradentes');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('05/09/17','DD/MM/RR'),null,null,'Elevação do Amazonas à categoria de Província (est.)');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('08/12/17','DD/MM/RR'),null,null,'Dia de Nossa Senhora da Conceição (est.)');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('14/04/17','DD/MM/RR'),null,null,'Sexta-feira Santa');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('15/06/17','DD/MM/RR'),null,null,'Corpus Christi');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('01/01/17','DD/MM/RR'),null,null,'Confraternização Universal');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('07/09/17','DD/MM/RR'),null,null,'Independência do Brasil');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('20/11/17','DD/MM/RR'),null,null,'Consciência Negra (est.)');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('01/05/17','DD/MM/RR'),'3',null,'Dia do Trabalho');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('28/02/17','DD/MM/RR'),null,null,'Carnaval');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('12/10/17','DD/MM/RR'),null,null,'Padroeira do Brasil');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('15/11/17','DD/MM/RR'),null,null,'Proclamação da República');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('25/12/17','DD/MM/RR'),null,null,'Natal');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('02/11/17','DD/MM/RR'),null,null,'Finados');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('20/05/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('27/05/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('03/06/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('10/06/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('17/06/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('24/06/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('01/07/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('08/07/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('15/07/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('22/07/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('29/07/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('05/08/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('12/08/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('19/08/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('26/08/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('02/09/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('09/09/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('16/09/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('23/09/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('30/09/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('07/10/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('14/10/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('21/10/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
Insert into WS4TI.CLIENTE_CALENDARIO (ID_CLIENTE,DT_CALENDARIO,ID_MAQUINA_GRUPO,ID_TURNO,DS_OBS) values ('1',to_date('28/10/18','DD/MM/RR'),null,null,'Fábrica parada no domingo');
