REM INSERTING into WS4TI.CLIENTE_TIPO_MANUTENCAO
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','PRE','Preventiva','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','COR','Corretiva','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','COI','Corretiva por interferência','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','ACO','Acompanhamento','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','SUP','Setup','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','BAN','Bancada','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','INS','Instalação','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','FER','Ferramentaria','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','PRD','Preditiva','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','P&M','Projetos e Melhorias','A');
Insert into WS4TI.CLIENTE_TIPO_MANUTENCAO (ID_CLIENTE,CD_TIPO,DS_TIPO,ST_TIPO) values ('1','IND','Indeterminado','A');
