REM INSERTING into WS4TI.CLIENTE_OS_MATERIAL
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_OS_MATERIAL (ID_CLIENTE,ID_OS,SQ_ITEM,DS_PRODUTO,DS_FORNECEDOR,VL_UNITARIO,QT_PRODUTO) values ('1','187','1','teste','teste','100','10');
