REM INSERTING into WS4TI.CLIENTE_GRUPO
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','12','Manutenção Industrial','manutindgeral@microservice.com.br','S','A','S','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','5','Extrusão Plástica',null,'N','A','N','S');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','7','Manutenção Predial','predialmns@microservice.com.br','S','A','S','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','4','Recursos Humanos','rh.manaus@microservice.com.br','S','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','6','Filmes',null,'N','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','11','Administração Industrial',null,'S','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','1','Estoque Materiais',null,'N','A','N','S');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','3','Controle de Qualidade',null,'N','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','8','Compras',null,'S','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','9','Fiscal',null,'S','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','10','Injeção Pástica',null,'S','A','N','N');
Insert into WS4TI.CLIENTE_GRUPO (ID_CLIENTE,ID_GRUPO,NM_GRUPO,DS_EMAIL,FL_ENVIA_EMAIL,ST_GRUPO,FL_ATENDE_OS,FL_ATENDE_FSSC) values ('1','2','Tecnologia da Informação','ti.servicedesk@microservice.com.br','S','A','N','N');
