REM INSERTING into WS4TI.CLIENTE_OS_CLASS
SET DEFINE OFF;
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','1','Elétrica','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','2','Hidraulica','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','3','Mecânica','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','4','Eletrônica','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','5','Pneumática','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','6','Processo','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','7','Setup','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','1001','Refrigeração','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','1000','Predial','A');
Insert into WS4TI.CLIENTE_OS_CLASS (ID_CLIENTE,ID_CLASS,DS_CLASS,ST_CLASS) values ('1','999','Indeterminado','A');
