REM INSERTING into WS4TI.DEMO_PRODUCT_INFO
SET DEFINE OFF;
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('1','Business Shirt','Wrinkle-free cotton business shirt','Mens','Y','50','image/jpeg','shirt.jpg',to_timestamp('02/03/18 09:48:54,163639000','DD/MM/RR HH24:MI:SSXFF'),'TOP SELLER');
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('2','Trousers','Black trousers suitable for every business man','Mens','Y','80','image/jpeg','pants.jpg',to_timestamp('02/03/18 09:48:54,206650000','DD/MM/RR HH24:MI:SSXFF'),'TOP SELLER');
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('3','Jacket','Fully lined jacket which is both professional and extremely comfortable to wear','Mens','Y','150','image/jpeg','jacket.jpg',to_timestamp('02/03/18 09:48:54,210085000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('4','Blouse','Silk blouse ideal for all business women','Womens','Y','60','image/jpeg','blouse.jpg',to_timestamp('02/03/18 09:48:54,212401000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('5','Skirt','Wrinkle free skirt','Womens','Y','80','image/jpeg','skirt.jpg',to_timestamp('02/03/18 09:48:54,214506000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('6','Ladies Shoes','Low heel and cushioned interior for comfort and style in simple yet elegant shoes','Womens','Y','120','image/jpeg','heels.jpg',to_timestamp('02/03/18 09:48:54,217407000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('7','Belt','Leather belt','Accessories','Y','30','image/jpeg','belt.jpg',to_timestamp('02/03/18 09:48:54,219841000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('8','Bag','Unisex bag suitable for carrying laptops with room for many additional items','Accessories','Y','125','image/jpeg','bag.jpg',to_timestamp('02/03/18 09:48:54,222087000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('9','Mens Shoes','Leather upper and lower lace up shoes','Mens','Y','110','image/jpeg','shoes.jpg',to_timestamp('02/03/18 09:48:54,224337000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into WS4TI.DEMO_PRODUCT_INFO (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS) values ('10','Wallet','Travel wallet suitable for men and women. Several compartments for credit cards, passports and cash','Accessories','Y','50','image/jpeg','wallet.jpg',to_timestamp('02/03/18 09:48:54,226648000','DD/MM/RR HH24:MI:SSXFF'),null);
