REM INSERTING into WS4TI.DEMO_TAGS_SUM
SET DEFINE OFF;
Insert into WS4TI.DEMO_TAGS_SUM (TAG,TAG_COUNT) values ('TOP SELLER','2');
Insert into WS4TI.DEMO_TAGS_SUM (TAG,TAG_COUNT) values ('REPEAT CUSTOMER','3');
Insert into WS4TI.DEMO_TAGS_SUM (TAG,TAG_COUNT) values ('LARGE ORDER','1');
