REM INSERTING into WS4TI.DEPT
SET DEFINE OFF;
Insert into WS4TI.DEPT (DEPTNO,DNAME,LOC) values ('10','ACCOUNTING','NEW YORK');
Insert into WS4TI.DEPT (DEPTNO,DNAME,LOC) values ('20','RESEARCH','DALLAS');
Insert into WS4TI.DEPT (DEPTNO,DNAME,LOC) values ('30','SALES','CHICAGO');
Insert into WS4TI.DEPT (DEPTNO,DNAME,LOC) values ('40','OPERATIONS','BOSTON');
