REM INSERTING into WS4TI.PARAM_OS_EVENTO_TIPO
SET DEFINE OFF;
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('AAT','Atendimento','A','EAT','S');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('AOS','Abertura OS','A','PEN','S');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('ENI','Enviar Informação','A',null,'S');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('FIA','Finalizar OS','A','ATE','N');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('FOS','Fechar OS','A','FEC','N');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('ROS','Reabrir OS','A','REA','N');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('SOI','Solicitar Informação','A',null,'S');
Insert into WS4TI.PARAM_OS_EVENTO_TIPO (TP_EVENTO,DS_TIPO,ST_TIPO,ST_OS,FL_ATENDIMENTO) values ('COS','Cancelar OS','A','CAN','N');
