REM INSERTING into WS4TI.PARAM_OS_STATUS
SET DEFINE OFF;
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('PEN','Pendente','S','S',null,null,'ORANGE');
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('EAT','Em atendimento','N','N',null,null,null);
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('INF','Informação','S','N',null,null,'PURPLE');
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('ATE','Atendida','S','N',null,null,'LIMEGREEN');
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('FEC','Fechada','N','N',null,null,'GREEN');
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('CAN','Cancelada','S','N',null,null,'GRAY');
Insert into WS4TI.PARAM_OS_STATUS (ST_OS,DS_STATUS,FL_ENVIA_EMAIL,FL_CANCELADO,NR_NIVEL,NR_PRIORIDADE,DS_COR_AGENDA) values ('REA','Reaberta','S','N',null,null,'RED');
