--------------------------------------------------------
--  DDL for Index UN_CLIENTE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "WS4TI"."UN_CLIENTE_EMAIL" ON "WS4TI"."CLIENTE_USUARIO" ("DS_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;
